#!/bin/bash

mkdir -p ./build
cd ./libxml2
autoreconf -if -Wall
cd ../build
emconfigure ../libxml2/configure --with-http=no --with-ftp=no --with-python=no --with-threads=no --with-modules=no
emmake make
cd ..
